import type { Metadata } from "next";
import { SideBarLayout } from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-[240px_1fr] min-h-screen w-full bg-background">
      <SideBarLayout />
      {children}
    </div>
  );
}
